### PR TITLE
#5 implement save task functionality

### PR DESCRIPTION
**Pull request by BojanJakic**

### CODE REVIEW

**Review by nikola-lisac — COMMENTED** [review]
Rename TaskServiceImpl to TaskService and delete TaskService interface.
It is not needed, because we will only have one implementation class.

**Review by nikola-lisac — APPROVED** [review]

**Comment by cctraining** [comment]
Make fields final

**Comment by DraganKec** [comment]
Maybe use  the singular `@PostMapping(value = "/task")` because we save only one task.

**Comment by nikola-lisac** [comment]
Add CrossOrigin annotation to controller and enable all origins, we will improve it later.
https://spring.io/blog/2015/06/08/cors-support-in-spring-framework

**Review by nikola-lisac — COMMENTED** [review]
By convention REST endpoints should be plural, so leave it as:  /tasks

**Comment by nikola-lisac** [comment]
Put CrossOrigin annotation on the controller instead of the method

**Review by cctraining — APPROVED** [review]

**Pull request merged**
