### PR TITLE
#3 create mysql schema

### PR DESCRIPTION
**Pull request by GojkovicGoran**

### CODE REVIEW

**Review by nikola-lisac — COMMENTED** [review]
- .idea folder should be in gitignore
- change the data type for "completed" column to tinyint

**Review by BojanJakic — APPROVED** [review]
Everything works fine, just pay attention on Nikola's comment

**Review by nikola-lisac — APPROVED** [review]

**Comment by cctraining** [comment]
Why do we need priority-tasks.sql and task.sql?

**Comment by nikola-lisac** [comment]
My bad, we don't need both.
One main script priority-tasks.sql  is enough.

**Comment by BojanJakic** [comment]
I just noticed that you missed to add AUTO_INCREMENT to id field

**Pull request merged**
